DROP TABLE "COMPTE";
DROP TABLE "CLIENT";
DROP TABLE "CREDIT";
DROP TABLE "LOG";


CREATE TABLE "CLIENT" (
    "LOGIN" VARCHAR(30) not null primary key,
    "NOM" VARCHAR(30),
    "PRENOM" VARCHAR(30),
    "PASSWORD" VARCHAR(20),
    "TYPE" VARCHAR(10) CONSTRAINT check_type CHECK(TYPE IN ('CLIENT', 'SUPERVISEUR', 'EMPLOYE'))
);

CREATE TABLE "COMPTE" (
    "ID" INTEGER not null primary key,
    "LOGIN_CLIENT" VARCHAR(30) CONSTRAINT ref_client REFERENCES CLIENT(LOGIN),
    "SOLDE" FLOAT
);

CREATE TABLE "LOG"(
    "ID" INTEGER not null primary key,
    "MESSAGE" VARCHAR(300)
);

CREATE TABLE "CREDIT"(
    "ID" INTEGER not null primary key,
    "INFOS_CLIENT" VARCHAR(300),
    "MONTANT" INTEGER,
    "TAUX" INTEGER,
    "DUREE" INTEGER,
    "SALAIRE" FLOAT,
    "CHARGE_CREDIT" INTEGER,
    "ACCORDE" VARCHAR(4)
);


INSERT INTO CLIENT VALUES('je', 'Fink', 'Jerome','je', 'CLIENT');
INSERT INTO CLIENT VALUES('oce', 'Seel', 'Oceane','oce', 'CLIENT');

INSERT INTO COMPTE VALUES(1, 'je',200000000);
INSERT INTO COMPTE VALUES(2, 'je',200);

INSERT INTO COMPTE VALUES(3, 'oce',5003);
INSERT INTO COMPTE VALUES(4, 'oce',56);
