DROP TABLE "COMPTE";
DROP TABLE "CLIENT";
DROP TABLE "CREDIT";
DROP TABLE "LOG";


CREATE TABLE "CLIENT" (
    "ID" INTEGER not null primary key,
    "NOM" VARCHAR(30),
    "PRENOM" VARCHAR(30),
    "LOGIN" VARCHAR(30),
    "PASSWORD" VARCHAR(20)
);

CREATE TABLE "COMPTE" (
    "ID" INTEGER not null primary key,
    "ID_CLIENT" INTEGER CONSTRAINT ref_client REFERENCES CLIENT(ID),
    "SOLDE" INTEGER
);

CREATE TABLE "LOG"(
	"ID" INTEGER not null primary key,
    "MESSAGE" VARCHAR(300)
);

CREATE TABLE "CREDIT"(
	"ID" INTEGER not null primary key,
    "INFOS_CLIENT" VARCHAR(300),
    "MONTANT" INTEGER,
    "TAUX" INTEGER,
    "DUREE" INTEGER,
    "SALAIRE" INTEGER,
    "CHARGE_CREDIT" INTEGER,
    "ACCORDE" VARCHAR(4)
);


INSERT INTO CLIENT VALUES(1, 'Fink', 'Jerome', 'je', 'je');
INSERT INTO CLIENT VALUES(2, 'Seel', 'Oceane', 'oce', 'oce');

INSERT INTO COMPTE VALUES(1, 1,200000000);
INSERT INTO COMPTE VALUES(2, 1,200);

INSERT INTO COMPTE VALUES(3, 2,5003);
INSERT INTO COMPTE VALUES(4, 2,56);

