/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import EntityClass.Client;
import java.awt.CardLayout;

/**
 *
 * @author John
 */
public class frameClient extends javax.swing.JFrame {
    
    private Client curUser;

    /**
     * Creates new form frameClient
     */
    public frameClient() {
        initComponents();
    }
    
    
    
    public void setCurUser(Client c)
    {
        curUser = c;
    }
    
    
    public Client getUser()
    {
        return curUser;
    }
    
    
    
    public void changeCard(String cardName)
    {
        CardLayout cl = (CardLayout)this.getContentPane().getLayout();
        cl.show(this.getContentPane(), cardName);
    }
    
    
    
    public VirementPanel getVirementPanel()
    {
        return virementPanel;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connexionPanel2 = new GUI.ConnexionPanel();
        virementPanel = new GUI.VirementPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(connexionPanel2, "connexion");
        getContentPane().add(virementPanel, "virement");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.ConnexionPanel connexionPanel2;
    private GUI.VirementPanel virementPanel;
    // End of variables declaration//GEN-END:variables
}
