/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import EJBApplicFinal.EJB2Remote;
import EntityClass.Compte;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJBException;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

/**
 *
 * @author Jerome
 */
public class virementAutreComptePanel extends javax.swing.JPanel {
    
    private Compte source;
    private VirementPanel panelPere;

    /**
     * Creates new form virementAutreComptePanel
     */
    public virementAutreComptePanel() {
        initComponents();
        errorvirementLabel.setVisible(false);
        okLabel.setVisible(false);
    }
    
    public void setPanel(Compte curCompte, VirementPanel father)
    {   
        source = curCompte;
        panelPere = father;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinataireLabel = new javax.swing.JLabel();
        destinataireTextField = new javax.swing.JTextField();
        montantLabel = new javax.swing.JLabel();
        montantTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        transfertButton = new javax.swing.JButton();
        errorvirementLabel = new javax.swing.JLabel();
        okLabel = new javax.swing.JLabel();

        destinataireLabel.setText("Compte destinataire : ");

        montantLabel.setText("Montant : ");

        jLabel1.setText("€");

        transfertButton.setText("Transferer");
        transfertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfertButtonActionPerformed(evt);
            }
        });

        errorvirementLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorvirementLabel.setText("jLabel2");
        errorvirementLabel.setToolTipText("");

        okLabel.setForeground(new java.awt.Color(0, 204, 0));
        okLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okLabel)
                    .addComponent(errorvirementLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(destinataireLabel)
                        .addGap(12, 12, 12)
                        .addComponent(destinataireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(montantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(montantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transfertButton)
                            .addComponent(jLabel1))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinataireLabel)
                    .addComponent(destinataireTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(montantLabel)
                    .addComponent(montantTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(errorvirementLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(transfertButton)
                .addGap(18, 18, 18)
                .addComponent(okLabel)
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transfertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfertButtonActionPerformed
        
        errorvirementLabel.setVisible(false);
        okLabel.setVisible(false);
        
        int idDest;
        double montantVirement;
        
        try
        {
            idDest = Integer.parseInt(destinataireTextField.getText());
        }
        catch(NumberFormatException ex)
        {
            errorvirementLabel.setText("ID de compte bancaire invalide");
            errorvirementLabel.setVisible(true);
            return;
        }
        
        try
        {
            montantVirement = Double.parseDouble(montantTextField.getText());
        }
        catch(NumberFormatException ex)
        {
            errorvirementLabel.setText("Le montant entré est invalide");
            errorvirementLabel.setVisible(true);
            return;
        }
        
        if(source == null)
            System.err.println("minnnnce");
        try
        {
            lookupEJB2Remote().sendMoney(source.getId(), idDest, montantVirement);
        }
        catch(EJBException ex)
        {
            errorvirementLabel.setText(ex.getMessage());
            errorvirementLabel.setVisible(true);
            return;
        }
        
        
        //Mise à jour des combos dans le panel pere
        okLabel.setText("Transfert reussi");
        okLabel.setVisible(true);
        
        montantTextField.setText("");
        destinataireTextField.setText("");
        panelPere.refresh();
    }//GEN-LAST:event_transfertButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel destinataireLabel;
    private javax.swing.JTextField destinataireTextField;
    private javax.swing.JLabel errorvirementLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel montantLabel;
    private javax.swing.JTextField montantTextField;
    private javax.swing.JLabel okLabel;
    private javax.swing.JButton transfertButton;
    // End of variables declaration//GEN-END:variables

    private EJB2Remote lookupEJB2Remote() {
        try {
            Context c = new InitialContext();
            return (EJB2Remote) c.lookup("java:comp/env/EJB2");
        } catch (NamingException ne) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "exception caught", ne);
            throw new RuntimeException(ne);
        }
    }
}
