/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author Jerome
 */
public class frameEmploye extends javax.swing.JFrame {

    /**
     * Creates new form frameEmploye
     */
    public frameEmploye() {
        initComponents();
    }
    
    public void changeCard(String cardName)
    {
        CardLayout cl = (CardLayout)this.getContentPane().getLayout();
        cl.show(this.getContentPane(), cardName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connexionPanel1 = new GUI.connexionPanel();
        creditPanel1 = new GUI.creditPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(connexionPanel1, "connexion");
        getContentPane().add(creditPanel1, "credit");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.connexionPanel connexionPanel1;
    private GUI.creditPanel creditPanel1;
    // End of variables declaration//GEN-END:variables
}
